### ISSUE TITLE
HomeWorkTaskScreen

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#120]
1. Nach einem Check will ich auch submitten/weiterarbeiten können.
2. Bei einem Check ist ein "your answer was correct" nicht sehr aussagekräftig
3. Was sind Checks, was sind submits... i-wo erklärt? Krigt man das auch intuitiv mit?
4. Die current / previous buttons sehen Meh aus

**Comment by fabiomazzone** [comment]
+1 
Ist richtig hat mich auch gerade gestört das ich dann nurnoch next task drücken kann

**Comment by svdwall** [comment]
Bump, haben wir hier neuerungen?

**Comment by JustCarl** [comment]
Zur vollsten Zufriedenheit gelöst, bis weiter anerkungen gemacht werden
