### ISSUE TITLE
HomeWorks

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#121]
1. Man kann auch mit 0 submits left noch submitten (die werden negativ)
2. Checks hab ich nicht darauf getestet (10 mal is mir zu doof gewesen :D )

**Comment by fabiomazzone** [comment]
Syntax Checks Funktionieren gerade getestet 
Und den Bug beim Semantic check habe ich auch gerade gefixt, aber halt nur in meinem Branch
