### ISSUE TITLE
validate references statements on task creation

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#134]

**Comment by svdwall** [comment]
Was hast du dir vorgestellt?

**Comment by fabiomazzone** [comment]
Nichts besonderes ich teste nur einmal of das Reference Statement läuft und gebe feedback zurück falls es nicht so ist.

**Comment by fabiomazzone** [comment]
Ist eingebaut 849b58b236532102d9bcc39baca64725c8b3b369
