### ISSUE TITLE
Admin Tool - Role System

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#149]

**Comment by svdwall** [comment]
Steeeeeeht (vlt mach ichs noch etwas hübscher.....) testet ruhig ma rum

**Comment by fabiomazzone** [comment]
hab es jetzt auch im back-end fast vollständig eingebaut.
ich glaube es fehlen noch sämtliche checks in den controllern für homework und group

**Comment by svdwall** [comment]
Done in admintool
