### ISSUE TITLE
TaskScreen: Difficulty 

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#161]

**Comment by goldenticket** [comment]
wenn man eine schwierigere Difficulty nimmt, aber keins vorhanden ist bekommt man eins der nächst geringeren Stufe.... dies wird aber nirgends displayed oder erklärt.

**Comment by fabiomazzone** [comment]
ja genau des wegen soll ja die schwierigkeits stufe angezeit werden von der task

**Comment by JustCarl** [comment]
Jojo
