### ISSUE TITLE
Can't reset story progress

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#163]
Wenn man den Story Progress zurücksetzten will, kann man nicht auf den "yes I am sure" button klicken.

**Comment by svdwall** [comment]
Tatsächlich scheint die story zu resetten, der user bekommt noch keine direkte rückmeldung, bis er den Story-screen betrachtet

**Comment by svdwall** [comment]
Und es scheint, dass man derzeit die page reloaden muss, damit er im frontend sinnvoll wirksam wird.

**Comment by fabiomazzone** [comment]
hab ich bisschen was dran gemacht man wird nun zum default Screen bei den settings geworfen und bekommt eine Meldung über den status der operation
