### ISSUE TITLE
veeeery long loading times

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#166]
SQLAclhemist lädt extrem lang, und scheint auch nicht wirklich irgendwas zu cachen. Kann man da was machen?

**Comment by svdwall** [comment]
ich kann nach dem ersten loading recht fix nachladen. (ca 10 sek) das erste mal dauert halt ewig...

**Comment by fabiomazzone** [comment]
aber wir haben schon ein issue in dem wir uns damit beschäftigen wollten die speichergröße zu reduzieren. #110
