### ISSUE TITLE
HMS abgleich

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#167]
was passiert, wenn jemand eine nicht eigene y-nummer dazutut?

**Comment by fabiomazzone** [comment]
Dann wird dem benutzer diese zugewiesen und der eigentliche besitzer kann die nicht mehr nehmen

**Comment by fabiomazzone** [comment]
kommt hier noch was ? :D 
Tipps und Ideen zur Verifikation werden hier gerne angenommen :dart:
