### ISSUE TITLE
Tutorial: Gürtelgrafik falsch plaziert

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#168]
Im Tutorial paralell zum Text "With this Scroll you can brew a Potion. Drinking them might..." ist ein merkwürdiges Duplikat der Gürtelgrafik mitten im Raum.

**Comment by svdwall** [comment]
Das Problem scheint in der aktuellen (lokalen) Version behoben

Edit: Issue wird geschlossen, sobald die version oben ist.
