### ISSUE TITLE
X Scrolls a day

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#174]
Einer unserer extra-eifrigen Studenten der zu früh sich angemeldet hat behauptet, dass sich das Scroll-Limit pro Tag nicht zurücksetzten würde über Nacht. Kann das sein?

**Comment by fabiomazzone** [comment]
Die Anzahl der Scroll die man für den aktuellen Tag einsammeln kann wird erst berechnet wenn man die erste Scroll eingesammelt hat glaube ich :D 
Müsste ich mal gucken.

**Comment by fabiomazzone** [comment]
Hab das jetzt so umgebaut das dieser wert nicht mehr in der Datenbank gecached wird.
