### ISSUE TITLE
Task Delivering on "Stay in TaskSet"

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#176]
Nachdem ich mir "Stay in TaskSet" anhab werden auch andere difficulty levels delivered.

**Comment by svdwall** [comment]
KP ob da der fehler im FE oder im BE liegt.

**Comment by fabiomazzone** [comment]
Bitte ? Nochmal :D

**Comment by fabiomazzone** [comment]
du müsstest eine Task aus dem selben Set erhalten und eine Aufgabe auf dem selben Schwierigkeitsgrad, nur bekommst nur eine leichtere wenn es keine mehr gibt auf dem Niveau

**Comment by svdwall** [comment]
und wenn es 2 gibt? auf dem gleichen niveau?

**Comment by fabiomazzone** [comment]
dann kommt es darauf an ob ich die andere task schon gemacht habe oder nicht :D
Ich gebe zu an der logik für das ausliefern der tasks muss  noch gearbeitet werden :D

**Comment by svdwall** [comment]
:) Ok, dann schauen wir uns das an^^

**Comment by JustCarl** [comment]
Frontend teil gemacht.

**Comment by ChristophLo** [comment]
Bedeutet das auch das jetzt der Schwierigkeitsgrad korrekt angezeigt wird?
(i.e., ich will ne 6Stern-Aufgabe, bekomme aber nur ne 4 Stern weil es keine 5er/6er gibt. Dann steht bei mir immernoch 6Stern oben im Interface - und ich komme mir voll toll vor weil ich super schwierige aufgaben einfach lösen kann plötzlich....)

**Comment by fabiomazzone** [comment]
also eigentlich sollte der richtige Schwierigkeitsgrad angezeigt werden
