### ISSUE TITLE
Tutorial: Infinite Loop ...  And others...

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#177]
Beginn mal das tutorial und mach das erste Level :D du wirst ihn schnell finden

Edit: geht nur, wenn du vor dem Level "Skip one" klickst

**Comment by svdwall** [comment]
Zusätzlich bekomme ich nicht die defense-potion-scroll...

**Comment by svdwall** [comment]
Auch hab ich kein Coin collection "Pling" (oben auf den butten klicken bringt nix. nur N gibt mir wieder sounds

**Comment by JustCarl** [comment]
Das liegt daran, dass das Scroll limit überschritten ist.
Das das Klicken nicht funktioniert liegt an den Buttons, dass sind noch keine Html buttons, also hat Chrom da kein Bock drauf, müsste man auch ersetzten.

**Comment by fabiomazzone** [comment]
Das Scrolllimit wird korrekt vom back-end ausgeliefert es befindet sich jetzt aber unter der Variable  game.data.user.scrollLimit im front-end zu finden, also aufjedenfall ist es dort einmal :D

**Comment by fabiomazzone** [comment]
f802f51 der bug sollte mit diesem commit behoben sein
