### ISSUE TITLE
Probleme mit Account verification.

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#187]
Wenn man seinen Account löscht und ihn mit seiner y-Nummer verifiziert hat, kann man die y-Nummer in seinem neuen Account nicht mehr nutzen.

**Comment by fabiomazzone** [comment]
Was soll mit den Kommentaren, Ratings, und Tasks passieren wenn sich ein User löscht ?

**Comment by goldenticket** [comment]
auf einen extra dafür erstellten User übertragen?

**Comment by fabiomazzone** [comment]
Vielleicht ist das ein besserer Ansatz:
- Benutzer die sich löschen werden wie bisher mit einer gelöscht-Flag markiert.
- Felder die Unique sind werden auf Null gesetzt oder verfälscht, sprich die Felder werden irgendwie in klammern gesetzt.
  Den Benutzer wirklich aus der Datenbank zu löschen bedeutet das seinen erstellten Content einem dump Account übergeben müssten und wir würden alle Verknüpfungen in der Log Tabelle verfälschen.

Vorschläge und / oder Kritik ?

**Comment by svdwall** [comment]
klingt prinzipiell nach einem plan. könten wir umgekehrt nicht einfach dem log seine Foreign Keys abnehmen? Brauchen wir die im Log?

**Comment by fabiomazzone** [comment]
ich würde sagen ja damit wir sehen ob derjenige ein student ist wie lange es den schon gibt und keine Ahnung was sich alles mit dem verknüpfen lässt
