### ISSUE TITLE
Admin Tool->TaskSet->TableDefinition

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#19]
Sören hier bitte nach ID sortieren :D

Ist voll doof wenn es nach TableName sortiert ist und du eine Table ändern willst, die springt dann einfach in der Liste herum :D

**Comment by svdwall** [comment]
Ja weiß ich :D aber is ok machen wa, dauert mich 2 sekunden :dancer:
