### ISSUE TITLE
Admininterface: Man kann keie Tasks löschen

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#191]
...ist jetzt nicht so schlimm, geht ja direkt in der Datenbank. Low Priority.

**Comment by ChristophLo** [comment]
Wieso invalid? Ich kann wirklich keine Tasks löschen?!

**Comment by fabiomazzone** [comment]
Da hab ich mich verklickt, ups

**Comment by svdwall** [comment]
war auch von dem message delivernment nicht ganz so schön. Sollte jetzt etwas klarer sein.

(solved Tasks können bis jetzt weiterhin nicht löschbar sein.)

**Comment by fabiomazzone** [comment]
ja, daran wollte ich mich gleich auch noch setzen :D

**Comment by fabiomazzone** [comment]
Hab ich jetzt umgesetzt, werde mich heute Mittag dann mal daran setzten, die neuen Funktionen und Fixes auf den Server zu pushen.
