### ISSUE TITLE
Time Spent nicht richtig

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#194]
Paul sagt:
Kleiner Bug: Time Spent wird im Ranking nicht richtig berechnet. D.h., dass die Zeit hochgeht, obwohl man nicht eingeloggt ist. Außerdem habe ich anscheinend innerhalb von 12 Stunden 2 Tage im Spiel verbracht.

**Comment by fabiomazzone** [comment]
Den Fehler sind @JustCarl  und ich genau durch gegangen und konnten hoffentlich das Problem lösen.
