### ISSUE TITLE
Endboss-Katze

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#195]
Maximilian sagt:
Der Text, der erscheint, wenn man einen Endboss das erste mal sieht und ihn nicht schafft (Sie brauchen mehr Tränke und...) kann nicht weggeklickt werden und verschwindet nicht. 
Nur aktualisieren der Seite hilft.

**Comment by JustCarl** [comment]
Der Sound zum Text startet eine Funktion die die Zustandsändererung bewirkt sobald der Sound zu Ende ist. Tabt man aus dem Browser hört man den Sound noch, aber alle anderen Prozesse sind auf Eis gelegt und werden erst wieder aufgenommen, wenn man in den Browser Tabt, nach einer gewissen Zeit sollte die Zustandänderung dann kommen.

**Comment by JustCarl** [comment]
Hab dem text noch nen Skipbutton verpasst
