### ISSUE TITLE
Moderate Healing Potion

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#196]
Maximilian sagt:
Der Trank der Moderate Healing Potion wird im Tränkebrauer nicht angezeigt. (Im Gürtel nur, solange man im Dungeon ist)
Ebenso zeigt der Zähler, der die Anzahl der Tränke anzeigt, die noch im Schrank sind erst die aktualisierte Anzahl an, wenn man erneut auf den Gürtel klickt.

**Comment by ChristophLo** [comment]
Gilt auch für Great Health Potion und Insane Healing Potion.

**Comment by vonunwerth** [comment]
Gilt auch für die Insane Jump Potion

**Comment by JustCarl** [comment]
Hab einen Fix angewandt, muss noch getestet werden.

**Comment by JustCarl** [comment]
Fehler behoben
