### ISSUE TITLE
Scroll-Reset Zeitpunkt auf die Nacht verlegen

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#198]
Angeblich ist der Reset gegen Mittag (zwischen 12-14 Uhr). Kann das sein?

**Comment by fabiomazzone** [comment]
der Reset ist immer 24h stunden nach dem eine Scroll eingesammelt wurde.

**Comment by ChristophLo** [comment]
Mhhh...ok. Ist das gut so?
Oder sollte das nicht irgendwann um 4 Nachts sein? (finde ich semantisch einfacher : "6 scrolls pro Zeitraum in dem ich wach bin")

**Comment by fabiomazzone** [comment]
Okay hab die Funktion jetzt umgeschrieben und auf den Server geschoben, kann getestet werden
