### ISSUE TITLE
Admin Tool

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#21]
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/adminapp/scripts/libraries/ui-ace.min.js 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/adminapp/scripts/libraries/mode-sql.js 
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by svdwall** [comment]
jaaaaa...^^

**Comment by svdwall** [comment]
fixed...hopefully?
