### ISSUE TITLE
Scroll-Anzeige

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#211]
Paul sagt:

Bei mir wird momentan nichts mehr bei der Übersicht für die eingesammelten Schriftrollen (Scroll-Scroll?) angezeigt.
Da ist also lediglich der Hintergrund (Schriftrolle), wenn ich auf diesen Stapel von Schriftrollen klicke.

Das wurde direkt so, nachdem ich die letzte Schriftrolle aus dem Eislevel eingesammelt hab. Hab auch bereits zwei weitere eingesammelt, was aber auch nichts an der Anzeige geändert hat.
Funktioniert weder bei Firefox, noch bei Chrome.

**Comment by goldenticket** [comment]
ist behoben.
