### ISSUE TITLE
solvedsubtask & Statistik

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#212]
Hey! Ich wollte gestern mal ein bisschen Statistik erstellen, und hab dazu in der Datenbank rumgewühlt.
Ich nehme mal an, das "Log" für Statistik ist in der Tabelle "solvedsubtask", korrekt?
Leider ist diese Tabelle nahezu ungeeignet, um damit Statistik zu machen da ihr da Daten schon halb-aggregiert. Das ist leider (obwohl lieb gemeint und aufwendiger) sehr unnütz. 
Deutlich besser wäre einfach eine ganz dumpfe Tabelle, die nach jedem Versuch ein SQL Statement zu lösen ein Log eintrag macht mit ("UserId, TaskID, Sucessful?, TimeNeeded, Timestamp").
Wenn ich dann aggregatstatistik brauche mit "Wie oft wurde das gleiche Statement von einem Nutzer gelöst, dann mache ich das einfach per SQL...
Leider ist die Statistik sehr wichtig (v.a. für die Weiterfinanzierung! > Stichwort Evaluation und Folgeanträge), daher müsste das sehr bald geändert werden. (Werft die alten Daten bitte daher nicht weg... bzw, ich ripp die dann eben nochmal vorher raus aus der DB?)

**Comment by fabiomazzone** [comment]
wie genau möchtest du denn die Zuweisung haben ? 
möchtest du genau sehen welcher Benutzer welche Aufgabe wann gemacht hat und ob die bestanden wurde ? 
Das Problem ist dabei nur das wenn die Aufgabe oder der Benutzer gelöscht werden auch die Daten im Log verloren gehen
