### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#213]
...vielleicht kann man ja die Email Verification erzwingen, statt optional (so, im Sinne der Spamaccount verminderung)

**Comment by fabiomazzone** [comment]
Finde ich ist eine Gute Idee, dann sollte aber auch auf dem Screen für die Registrierung ein Hinweis stehen das man sich nur mit einer Validierten E-Mail einloggen kann.

**Comment by fabiomazzone** [comment]
Eventuell sollte bei jedem Log-in Versuch eine neue Email mit dem Code zur Verifikation losgeschickt werden bzw. müsste es einen neuen Screen geben, auf dem eine neue Validations-Email angefordert werden kann.

**Comment by fabiomazzone** [comment]
Es würde sich dann auch anbieten die nicht verifizierten Nutzer die älter als eine Woche oder vielleicht sogar ein Monat sind automatisch zu löschen.
