### ISSUE TITLE
Backend interface schon wieder kaputt???

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#214]
Öhhh...ich versuche gerade ein neues Taskset anzulegen. Dabei sind 3 Stück entstanden, die Intensionen funktionieren schon wieder nicht, was issn da los schon wieder?? Das ging doch noch vor 2 Wochen?

**Comment by fabiomazzone** [comment]
Bei mir funktioniert, dass noch ? .. 
Wo liegt denn genau der Fehler ?

**Comment by ChristophLo** [comment]
Wenn ich neue Etensions einfüge werden die nicht in der DB gespeichert.

**Comment by fabiomazzone** [comment]
Vielleicht gibt es ein Problem mit der Extension ?
Also eigentlich sollte dann ein Fehler an dich zurück gegeben werden, das gucke ich mir nochmal dein.

**Comment by ChristophLo** [comment]
Ich kann jetzt keine neuen Tasks anlegen.... komisch alles... (im Hotel taskset, in Potion gehts....)

**Comment by svdwall** [comment]
interessant. ich frage mich, warum das Admintool keine Fehler ausgibt. ich sehe mir das auch mal an.

**Comment by svdwall** [comment]
Wie vermutet. Scheint keinen Error anzuzeigen, da es im Admintool falsch war.

**Comment by gabrielahlers** [comment]
Neues Taskset anlegen, Extensions einfügen hat heute bei mir reibungslos funktioniert.

Tasks erstellen geht immernoch nicht @Invisible4ever

**Comment by svdwall** [comment]
Tasks sollten nun erstellt werden

Bitte weiter im Auge behalten

**Comment by fabiomazzone** [comment]
und wie sieht es hier aus ?

**Comment by svdwall** [comment]
Die Errors werden jetzt korrekt im AT angezeigt

**Comment by fabiomazzone** [comment]
super :+1: 
Also ist das issue doch eigentlich erledigt, oder nicht ?

**Comment by svdwall** [comment]
denke schon.
