### ISSUE TITLE
Nach dem Createn der ersten potion

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#216]
Soll man zurück in den Main Screen. Der übergang ist nicht intuitiv gestaltet:
- Man bekommt anweisung die potion in den belt zu tun
- Verlässt man verfrüht den potion/belt screen wird man zurück bekommt man die korrekte message, die potion in den belt zu setzen.
- Danach ist nicht klar, dass man den back button drücken soll.

**Comment by JustCarl** [comment]
Fixed, need to be pushed
