### ISSUE TITLE
Datentyp für Table-Extension in MySQL falsch

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#217]
Der Datentyp für die Table-Extensions ist "text". Das ist ein Limit von 65535 Bytes. Meine Aktuelle Etension hat mehr als 120k Bytes, passt da also nicht rein. Daher: Datentyp ändern von "text" auf "mediumtext". (würde das ja auch selber machen, weiss aber nicht ob das irgendwo noch referenziert wird in eurem code...)

**Comment by fabiomazzone** [comment]
als neuen Datentyp hinzugefügt mit: 828a7b777567ec380c2882de805175594106d520
Muss noch noch auf den Server deployed werden

**Comment by fabiomazzone** [comment]
hab jetzt einfach denn datentypen per alter table statement geändert
