### ISSUE TITLE
Minigame: Auf Gegner springen

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#218]
Paul sagt: Das Abspringen von Gegnern funktioniert manchmal sehr unterschiedlich. So fällt man öfter durch Gegner, wo man eigentlich klar auf sie gelandet wäre, oder springt von Gegner ab, die man eigentlich nur an der Seite berührt hat. Eben konnte ich auch 2 Mal hintereinander vom selben Gegner abspringen (Spielfigur war an der Wand, deshalb selbe X-Position), wobei es aber beim 3. Mal nicht mehr ging.
Edit: Außerdem wird man auch öfter mal von Gegnern "getroffen", wenn man auf sie springt. 

Edit: In der Dschungel-Welt hängt man teilweise vor den Wänden. 
Außerdem springt man höher, wenn man an einer Wand "klebt" und dann springt.

**Comment by JustCarl** [comment]
Das Minispiel soll etwas frustieren, der Walljump ist gewollt. Wenn es nicht sehr viele weitere Beschwerden gibt, würde ich das Minispiel so lassen.
