### ISSUE TITLE
TaskScreen: SQL Highlighting 

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#222]
Die Keywords in IN oder IS werden nicht gehighlightet

**Comment by JustCarl** [comment]
exists, intersect, except Sind bestimmt noch weitere

**Comment by svdwall** [comment]
mach ich fix

**Comment by svdwall** [comment]
sagt bescheid, wenn noch was soll

**Comment by fabiomazzone** [comment]
guck einfach mal in den H2 standard was es dort alles gibt und bau die alle ein :D

**Comment by svdwall** [comment]
Did dat :)
