### ISSUE TITLE
see #97 Admininterface geht schon wieder nicht....kann immer noch keine Tasks anlegen....

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#227]
Man kann immer noch keine Tasks anlegen, diesmal kommt immer Reference Statement not runnable....
Das wäre wirklich nützlich, wenn ich so langsam weiter aufgaben bauen könnte - ist im Prinzip seit 2 Wochen kaputt...

![image](https://cloud.githubusercontent.com/assets/10435060/12516421/a959b5d0-c12d-11e5-8955-e0a7247a6395.png)

**Comment by fabiomazzone** [comment]
Unique index or primary key violation: "PRIMARY_KEY_2 ON PUBLIC.BOOKING(PERSON, HOTEL) VALUES (57, 79, 2)"; SQL statement: INSERT INTO booking VALUES (57, 79, '2016-01-13', 50, 2);
 [23505-187]
Das Ist der Fehler warum das TaskSet die ganze zeit nicht funktioniert

**Comment by fabiomazzone** [comment]
Das Problem ist wohl eher das es keine composite primary keys gibt

**Comment by fabiomazzone** [comment]
Wir müssten uns dafür noch eine angenehme Logik übernehmen wie wir composite primary keys definieren :D
vielleicht so ähnlich wie mit den foreigen keys, oder wir fügen hinter der CheckBox für Primary Key noch ein DropDown Feld um Gruppen für die PrimayKeys zu definieren

**Comment by fabiomazzone** [comment]
Okay ich bin dem Fehler gerade auf den Fersen, eigentlich sollte er kombinierte Keys können.

**Comment by fabiomazzone** [comment]
Diese Fehler kommen wir hoffentlich mit dem ticket #228 auf die Schliche.

**Comment by svdwall** [comment]
Hier haben wir ein Problem, oder?

``` java
TaskSet.getSQLStatements:
 for(TableDefinition tableDefinition : this.tableDefinitions) {
      sqlStatements.add(tableDefinition.getSQLStatement());
}
```

erzeugt:

``` sql
CREATE TABLE tbl (
col_1 INTEGER PRIMARY KEY,
col_2 INTEGER PRIMARY KEY
);
```

anstelle von

``` sql
CREATE TABLE tbl(
col_1 INTEGER,
col_2 INTEGER,
PRIMARY KEY(col_1,col_2)
);
```

oder?

**Comment by svdwall** [comment]
Nevermind, kommt richtig zurück

**Comment by svdwall** [comment]
Das ist jetzt #97

**Comment by fabiomazzone** [comment]
Fehler Endlich gelöst ! :+1: 
Das Problem war ganz einfach eine Verletzung der Primary Keys, In dem Schema konnten Gäste nicht mehrmals das selbe Hotel buchen. ich habe jetzt einfach das Datum noch mit hinzugefügt zum Primary  Keys.
