### ISSUE TITLE
Ausgeben der CREATE TABLE-Statements im AdminTool

### ISSUE THREAD

**Issue by gabrielahlers** [ifis-tu-bs/sqlalchemist#228]
Damit man diese einfach kopieren kann und zum Beispiel in einer eigenen Datenbank testen kann.

**Comment by fabiomazzone** [comment]
Im Back-End habe ich die Funktion umgesetzt.
Die Statement sind als String Array im Json nun unter dem Feld "sqlstatements" zu finden. 
@Invisible4ever dein Part nun :P

**Comment by fabiomazzone** [comment]
Ich werde auch im SQL Parser das Array nutzen. 
Es ist möglich das die Statements in einer Anderen Reihenfolge ausgegeben werden aber es bleibt immer die Basisreihenfolge
1. Create Table Statements
2. Alter Table    "
3. Extension

**Comment by fabiomazzone** [comment]
For request 'PATCH /API/TaskSet/14/' [Request Entity Too Large] 
Dadurch dass ich jetzt einfach die SQL Statements mit schicke wird Play! die Patch Request wohl zu lang. @Invisible4ever du musst einfach das Feld entfernen bevor du die Anfrage verschickst

**Comment by svdwall** [comment]
Bin dran

**Comment by svdwall** [comment]
Ok is done.

**Comment by gabrielahlers** [comment]
Ausgabe ist noch nicht implementiert/ oder vielleicht noch nicht auf dem Server? @Invisible4ever

**Comment by fabiomazzone** [comment]
ja weiß man nicht wie das geht wo das geht :D
