### ISSUE TITLE
DAS ADMIN INTERFACE GEHT NICHT!!! ICH KANN KEINE TASKS FÜR MORGEN ANLEGEN !

### ISSUE THREAD

**Issue by ChristophLo** [ifis-tu-bs/sqlalchemist#230]
AHHHHHHHHH!!!!!!!!!!
Warum!!?
Ich kann schon wieder keine Taks anlegen wegen dem doofen Reference-Statements.
Ich kann die Aufgaben für den Tag der Informatik nicht einstellen!
Das ist MIST!
Ich brauch das! Wir haben sonst morgen früh kein Exponat!
Kann doch nicht sein das seit 2 Wochen diese bekloppte Admininterface nicht läuft.

Also, wer auch immer sich berufen fühlt das heute Abend zu reparieren, dem wäre ich seeehr dankbar.
Ich versuche das Taskset TDI zu editieren, und ich möchte die tabellen/Extensionen/Aufgaben aus dem unten angehängten Textfile haben. Ich würds ja selber machen, aber wie gesagt, ist ja kaputt....

[data.sql.txt](https://github.com/ifis-tu-bs/sqlalchemist/files/103648/data.sql.txt)

**Comment by fabiomazzone** [comment]
Ähm, ja also ich denke das ist auf einen Bedienungsfehler zurück zuführen.
Hattest du irgendwie an der Datenbank was per Hand gemacht ?
Ich setze gerade das Schema mit Aufgaben im Admin-Tool Problemlos um nachdem ich alle Altlasten des Tasks gelöscht habe.
Vielleicht einfach öfter speichern, dann kommt es am Ende nicht zu großen und komischen Fehlern.

**Comment by ChristophLo** [comment]
Ne, hab ich nichts per Hand gemacht. Ich probiers gleich mal...

**Comment by ChristophLo** [comment]
Ohh....mhh...Ihr habt das ja gemacht.
Okey.
Hab ich mich da echt zu doof angestellt?`
Was war denn das Problem?
Anyway, vielen Dank!

**Comment by fabiomazzone** [comment]
Das problem war irgendwie das er die Fremdschlüssel nicht auflösen konnte und er warum auch immer keine Werte zu dem Taskset ausgegeben hat. musste in die Datenbank und alles Alte von Hand löschen.
