### ISSUE TITLE
PasswortReset und MailVerfification

### ISSUE THREAD

**Issue by goldenticket** [ifis-tu-bs/sqlalchemist#237]
Student hat Passwort vergessen, möchte reseten, bekommt aber die nachricht das die Mailadresse erst verifizieren muss.

**Comment by fabiomazzone** [comment]
also das kann ich jetzt nach vollziehen, 
im source code ist keine passage die ihm sagt das er eine Validierte Email brauch.
Es gibt eine Passage die sagt das er eine Valide Email Adresse angeben muss, sprich eine Email die dem Scheme asd@asd.asd folgen muss.
Darum wird das Ticket geschlossen.
