### ISSUE TITLE
HomeWork FE

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#51]

**Comment by goldenticket** [comment]
Call für die Homeworks funktioniert nicht Sören. Wir müssen da nochmal drüber reden.
GET http://localhost:9000/homework/tasks 404 (Not Found)

aus der api....
#HomeWorkController
GET /homework/tasks                     controllers.HomeWorkController.getCurrentHomeWorkForCurrentSession()

**Comment by goldenticket** [comment]
GET http://localhost:9000/Homework/student/1 404 (Not Found)
