### ISSUE TITLE
Schema Konventionen

### ISSUE THREAD

**Issue by JustCarl** [ifis-tu-bs/sqlalchemist#65]
# __ zum markieren von Tabellennamen

%__ zum markieren von Attributen
!**! für Keyattributes
{**} geschweifte Klammern um die einzelnen Tabellen voneinander abzugrenzen.

Bsp:
# Tabellenname { %!Attribut! : Datentyp, %Attribut : Datentyp, ....}

**Comment by svdwall** [comment]
ForeignKeys?!?

**Comment by svdwall** [comment]
Da es ein JSON ist, darf ich das etwas anpassen? Bsp:
[{
  "tableName" : "Table01",
  "columns" : [
    {
       "name": "id",
       "datatype" : "BIGINT",
       "isPrimary" : true
       "foreignKey" : null (oder aber {"tableName" : "TableXX", "columnName": "ColumnXX"})
    }
  ]
}]

**Comment by svdwall** [comment]
Kann natürlich auch einfach einen String machen für dich :D
