### ISSUE TITLE
HomeWork Create Dialog

### ISSUE THREAD

**Issue by fabiomazzone** [ifis-tu-bs/sqlalchemist#85]
Add some Inputfields for startime and endtime to the create homework dialog

**Comment by svdwall** [comment]
Should already be in there as the second accordion? Looking at that.

**Comment by svdwall** [comment]
Is already there, made more intuitive.

**Comment by fabiomazzone** [comment]
Im mean an Input field for the time not for the date, or set the endtime to 12 pm as default value.

**Comment by svdwall** [comment]
12 pm is set. i guess? ;D gonna try that

**Comment by svdwall** [comment]
yep. New homeworks get 0am - start date to 11:59:59 pm - expire date

**Comment by svdwall** [comment]
Rather choosable?

**Comment by fabiomazzone** [comment]
Yes i the database is the endtime 12 pm but not in the admin tool create dialog: Selected date is: Mon, 16 Nov 2015 11:47:16 GMT <------ :P

**Comment by fabiomazzone** [comment]
nope, only change the displayed time.

**Comment by svdwall** [comment]
its a relic of testing :D

**Comment by svdwall** [comment]
removed it
