### ISSUE TITLE
Combined Foreign Keys

### ISSUE THREAD

**Issue by svdwall** [ifis-tu-bs/sqlalchemist#97]

**Comment by svdwall** [comment]
#227 zeigt: es geht nicht ohne!

**Comment by fabiomazzone** [comment]
hab es auch noch nicht eingebaut :D 
Sag ich dir morgen wie wir das simple umsetzten

**Comment by fabiomazzone** [comment]
kommt gleich auf den Server :D

**Comment by svdwall** [comment]
wenn man einen key combined macht, speichert und ihn dann uncombined macht und erneut speichert, bekomm ich nen bug.

``` error
Referential integrity constraint violation: "CONSTRAINT_2E: PUBLIC.BOOKING FOREIGN KEY(PERSON, HOTEL) REFERENCES PUBLIC.CUSTOMER(ID, ID)"; SQL statement: ALTER TABLE booking ADD FOREIGN KEY (person, hotel) REFERENCES customer(id, id); [23506-187]
```

**Comment by fabiomazzone** [comment]
Das ist ein Bug weil du den kombinierst der Key denn du erstellt hast macht keinen Sinn deswegen kommt eine fehlermeldung :D Wenn ich das richtig verstehe sagst du ihm das er für Partner von Person und Hotel in der Tabelle Customer machen soll. Macht keinen Sinn bzw. Geht nicht also bekommst du eine Fehlermeldung :D

**Comment by fabiomazzone** [comment]
Okay, ja aber da gibt es einen Fehler, er speichert den Unsinnigen Key und man kann warum auch immer die kombinierten Schlüssel nicht trennen ...

**Comment by svdwall** [comment]
Das neue Problem hängt daran, dass die Überprüfung des TaskSets immer mit den TableDefinitions/ForeignKeyRelations aus der DB ausgeführt wird.
